name: karhabti_pfe
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_native_timezone: ^2.0.0
  fluttertoast: ^8.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
dependency_overrides:
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  

  # DateTime
  jiffy: ^5.0.0
  intl: ^0.17.0
  http: ^0.13.6
  # Images
  cached_network_image: ^3.2.0 
  image_picker: ^0.8.7+4
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  # Google Map
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.5
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  # Firebase And Notification 
  flutter_local_notifications: ^9.3.1
  firebase_messaging: ^14.5.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  geoflutterfire: ^3.0.3
  flutter_background_service: ^2.4.6
  
  # Local Data Cache
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0
  # Qrcode 
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.2
  dropdown_search: ^5.0.6
  badges: ^3.1.1
  # Icon 
  # flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  # Google Auth
  google_sign_in: ^6.1.0
  device_preview: ^1.1.0
  responsive_builder: ^0.6.4
  image_pickers: ^2.0.0+2
  table_calendar: ^3.0.8
  awesome_dialog: ^3.0.2
  flutter_osm_plugin: ^0.53.2
  flutter_map: ^3.1.0
  tuple: ^2.0.1
  positioned_tap_detector_2: ^1.0.4
  transparent_image: ^2.0.1
  vector_math: ^2.1.2
  proj4dart: ^2.1.0
  meta: ^1.7.0
  collection: ^1.16.0
  latlng: ^1.0.0
  latlong: ^0.6.1
  location: ^4.4.0
  file_picker: ^5.2.11
  package_info_plus: ^3.1.2
  dotted_border: ^2.0.0+1
  open_street_map_search_and_pick: ^0.0.12
  http_status_code: ^0.0.2
  flutter_calendar_carousel: ^2.4.1
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.18.6
  flutter_otp_text_field: ^1.1.1
  geoflutterfire2: ^2.3.15
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/login.png
    - assets/images/signup.png
    - assets/images/signup2.png
    - assets/images/gestion.png
    - assets/images/venach.png
    - assets/images/panne.png
    - assets/images/pannepage.png
    - assets/images/background.jpeg
    - assets/images/back2.jpeg
    - assets/images/loginorsignup.png
    - assets/images/ch-batt.png
    - assets/images/ch-clim.png
    - assets/images/deca.png
    - assets/images/frein.png
    - assets/images/profil.png
    - assets/images/vid.png
    - assets/images/diagnostic.png
    - assets/images/image1.png
    - assets/images/image21.png
    - assets/images/image22.png
    - assets/images/image2.png
    - assets/images/imagep.png
    - assets/images/image4.png
    - assets/images/background.png
    - assets/images/maps.jpg
    - assets/images/mecanicien.png
    - assets/images/lavage.png
    - assets/images/pneu.png
    - assets/images/tolier.png
    - assets/images/vitrage.png
    - assets/images/elect.png
    - assets/images/climatisation.png
    - assets/images/loc.png
    - assets/images/post.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/rendez-vous.png
    - assets/images/annonce.png
    - assets/images/batterie.png
    - assets/images/frais.png
    - assets/images/robot.png
    - assets/images/backgroundmsg.png
    - assets/images/frais2.png
    - assets/images/forgetpassword.png
    - assets/images/verifycode.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/font/Comfortaa-Light.ttf
        - asset: assets/font/Comfortaa-SemiBold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
